language: node_js
dist: bionic
addons:
  chrome: beta
branches:
  only:
    - master

env:
  global:
    - GOOGLE_CHROME_BINARY="/usr/bin/google-chrome-beta"
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

node_js:
  - '8'
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile

script:
  - node --version
  - yarn --version
  - yarn typecheck
  - yarn build
  - yarn test
  - yarn lint

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
